name: Primer workflow


on:
  workflow_dispatch:
  
  push:
    branches:
    - typescript

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.X
    
      - name: Install
        run: |
          npm ci --silent
          npm run build
        working-directory: .
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: build
        
    
